kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rtorrent-config
  namespace: media
  labels:
    app.kubernetes.io/instance: rtorrent
    app.kubernetes.io/name: rtorrent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi